### ISSUE TITLE
Issues with GitUtils

### ISSUE THREAD

**Issue by junjun-zhang** [ICGC-TCGA-PanCancer/OxoGWrapperWorkflow#2]
Please see the comments on this page: https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/commit/1dbc6abe10dd8084185e9c9240eab092e8eb4ef9#diff-ab679513789e1e06e26f13e5ce147375

When there are many jobs running in parallel _git push_ may fail causing the whole workflow fail.

**Comment by SolomonShorser-OICR** [comment]
I've switched from simple bash commands to using a python script similar to the one you linked to. See: https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/feature/get_to_first_run-through/workflow/scripts/git_move.py

**Comment by junjun-zhang** [comment]
Thanks @SolomonShorser-OICR, just a quick comment on this line: https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/feature/get_to_first_run-through/workflow/scripts/git_move.py#L93

As there will be a large number of Jobs running simultaneously, the chance of git conflict increases very fast if each jobs is fairly short. There is one thing very easy to do to ensure git mv retry success, that is to add more retries and sleep much short time between each re-try. Say re-try 50 times, and randomly sleep 0 - 2 seconds. In order to increase randomness, should use float number instead of integers, eg, sleep 1.235 seconds, Python _time.sleep_ function takes float numbers.

**Comment by SolomonShorser-OICR** [comment]
We currently estimate that jobs will require ~5 hours to run. This will vary by the size of the input files that the workflow needs to download. I believe that the size of the BAM files will have the biggest impact on running time because it will affect download time as well as the running time of processes that need to read the BAM files. So even if many workers all start at almost the same time, I think it is  unlikely they will transition to different states at the same time, or complete at the same time. I can increase the retries, but I think I'd also like to keep a larger window for sleep durations (1 to 15 second).

**Comment by denis-yuen** [comment]
You might get a bunch at the same time at the very beginning though, for example if youxia provisions 5 workers at the same time, you might see all five of them getting and starting jobs. I believe that we saw this kind of behaviour with store-and-forward.

**Comment by SolomonShorser-OICR** [comment]
True, though that also depends on batch size. We might want to create a fleet of 50 - 100 workers, though the batch size could be smaller than that. So it could happen that with a batch size of say 10, if a few of them have a collision when they try to work with git, they will have a retry-wait time of 1 - 15 seconds and they will retry up to 10 times, with a different retry-wait time on each retry.

**Comment by junjun-zhang** [comment]
It's an easy thing to change in the code, having more re-tries with shorter wait time does not do any harm either. Why not do it now instead of waiting until much more severe issue comes up? If we are talking about ~100 workers, it's going to be pretty hard to sort things out in case things go wrong.
