### ISSUE TITLE
Refactor docker commands/inline-scripts

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ICGC-TCGA-PanCancer/OxoGWrapperWorkflow#9]
The docker commands and scripts built in to the Java class could probably be refactored out to text templates and then populated with something like http://www.stringtemplate.org/ or maybe http://velocity.apache.org/engine/ 

Either way, there's a lot of potential for code cleanup!

**Comment by SolomonShorser-OICR** [comment]
Also consider jinjava: https://github.com/HubSpot/jinjava

**Comment by denis-yuen** [comment]
:+1:  sounds neat

**Comment by SolomonShorser-OICR** [comment]
This was introduced in 2.0.0.
